version: 0.2

phases:
  install:
    commands:
      - echo "Installing Terraform"
      - yum install -y unzip
      - curl -o terraform.zip https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_amd64.zip
      - unzip terraform.zip
      - mv terraform /usr/local/bin/
      - terraform --version

  pre_build:
    commands:
      - terraform init

  build:
    commands:
      - terraform plan
      - terraform apply -auto-approve
